services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 256M

  app:
    build: .
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/arabotiq-marketing
      - PORT=3000
      # Other environment variables should be set in production
    depends_on:
      - mongo
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  mongo:
    image: mongo:latest
    command: mongod --wiredTigerCacheSizeGB 0.25
    expose:
      - "27017"
    volumes:
      - mongo-data:/data/db
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

volumes:
  mongo-data: